pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building...'
                sh 'whoami'
                sh 'pwd'
                sh 'sudo rm -rf kubevirt'
                sh """
                sudo git clone "ssh://hanwei@gerrit.cmss.com:29418/EKI/kubevirt"
                cd kubevirt
                sudo git checkout -b devel origin/devel
                ls -l
                sudo make
                """
            }
        }
        stage('Push image') {
            steps {
                echo 'Testing...'
                // 根据需修改代码仓库位置和tag
                sh """
                export DOCKER_PREFIX=registry.eki/kubevirt
                export DOCKER_TAG=jenkins-xx
                sudo make push
                """
            }
        }
        stage('Ouput manifests') {
            steps {
                echo 'Ouput manifests...'
                sh 'sudo make manifests'
                // 目前是输出到屏幕，若有内部可以上传的地方可以添加上传
                sh 'cat _out/manifests/release/kubevirt-cr.yaml'
                sh 'cat _out/manifests/release/kubevirt-operator.yaml'
            }
        }
    }
}