# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 后端云
subtitle: 专注云原生融合技术：容器虚拟机融合，多云融合（混合云，分布式云，边缘云），高性能网络，融合监控
description: kubevirt openstack linux 虚拟机 容器 裸机 微服务 函数计算 kubernetes 异构计算 人工智能
keywords: kubevirt openstack linux  虚拟机 容器 裸机 微服务 函数计算 kubernetes 异构计算 人工智能
author: 后端云
language: zh-CN
timezone: ''

githubEmojis:
  enable: true
  className: github-emoji
  unicode: true
  styles:
    display: inline
    vertical-align: middle # Freemind适用
  localEmojis:


# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
url: https://www.backendcloud.cn
root: /
#url: https://www.backendcloud.cn/blog/h
#root: /blog/h/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: false
  auto_detect: true
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: true
  line_number: false
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 5
pagination_dir: page

archive_generator:
  per_page: 15  #值为0表示不分页，按需填写
  yearly: true  #是否按年生成归档
  monthly: false  #为了加快生成速度，按月归档就不要了

tag_generator:
  per_page: 15  #值为0表示不分页，按需填写
category_generator:
  per_page: 15  #值为0表示不分页，按需填写

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-3-hexo-master

# baidu analytics
baidu_analytics: 2858b2d509d28416712739c9a6a31204

readmore:
  enable: true
  blogId: '48072-1211879175079-403'
  name: '后端云'
  keyword: 'cloud'
  qrcode: 'https://www.backendcloud.cn/img/wechat-dingyuehao.jpg'
  random: 1

sitemap:
    path: sitemap.xml

# google_analytics: UA-90951221-1

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
#deploy:
#  type: rsync
#  host: 120.26.200.226
#  user: root
#  root: /usr/share/nginx/html/backendcloud/www/
#  #root: /usr/share/nginx/html/backendcloud/www/blog/h
#  port: 22
#  delete: true
#  verbose: true
#  ignore_errors: false
deploy:
  type: git
  repo: git@github.com:backendcloud/backendcloud-aliyun-cd.git
  # repo: git@github.com:backendcloud/backendcloud.github.io.git
  # example, https://github.com/hexojs/hexojs.github.io
  branch: main
  ignore_hidden:
    public: false

