name: HEXO CI

#Invalid workflow file: .github/workflows/ci.yml#L1
#  you may only define one of `paths` and `paths-ignore` for a single event
on:
  push:
    branches:
      - master # 只在master上push触发部署
      - main
#   pull_request:
#     branches:
#       - master # 只在master上merge触发部署
#    paths: # 有个坑。只能 - 'source/_posts/**' 形式， - './source/_posts/**' 就不可以
#      - 'source/_posts/**'
#      - 'source/images/**'
#      - 'source/files/**'
#    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
#      - README.md
#      - LICENSE
#    paths: # 这里是用来指定哪个文件更改，才会触发的 # 不起效果，暂时不明原因
#      - './source/_posts/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{ secrets.DEPLOY_KEY_NEW }}
        run: |
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "hanwei"
          git config --global user.email "backendcloud@gmail.com"
      - name: Install dependencies
        run: |
          npm i -g hexo-cli
          npm i
          npm install hexo-readmore --save
          npm install hexo-deployer-git --save
          npm install hexo-filter-github-emojis --save
      - name: Deploy hexo
        env:
          SSH_HOST_PRI: ${{ secrets.SSH_HOST }}
        run: |
          hexo clean && hexo generate
          mkdir -p ./public/.github/workflows
          cp ./backendcloud.aliyun.cd.yml ./public/.github/workflows/cd.yml
          hexo deploy
#          rsync --delete -avz ./public/ ${SSH_HOST_PRI}:/usr/share/nginx/html/backendcloud/www/



#name: Deploy site files
#
#on:
#  push:
#    branches:
#      - master # 只在master上push触发部署
#    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
#      - README.md
#      - LICENSE
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化脚本
#
#    steps: # 自动化步骤
#      - uses: actions/checkout@v2 # 第一步，下载代码仓库
#
#      - name: Deploy to Server # 第二步，rsync推文件
#        uses: AEnterprise/rsync-deploy@v1.0 # 使用别人包装好的步骤镜像
#        env:
#          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }} # 引用配置，SSH私钥
#          ARGS: -avz --delete --exclude='*.pyc' # rsync参数，排除.pyc文件
#          SERVER_PORT: "22" # SSH端口
#          FOLDER: ./public/ # 要推送的文件夹，路径相对于代码仓库的根目录
#          SERVER_IP: ${{ secrets.SSH_HOST }} # 引用配置，服务器的host名（IP或者域名domain.com）
#          USERNAME: root # 引用配置，服务器登录名
#          SERVER_DESTINATION: /usr/share/nginx/html/backendcloud/www/ # 部署到目标文件夹
##      - name: Restart server # 第三步，重启服务
##        uses: appleboy/ssh-action@master
##        with:
##          host: ${{ secrets.SSH_HOST }} # 下面三个配置与上一步类似
##          username: ${{ secrets.SSH_USERNAME }}
##          key: ${{ secrets.DEPLOY_KEY }}
##          # 重启的脚本，根据自身情况做相应改动，一般要做的是migrate数据库以及重启服务器
##          script: |
##            cd /home/fming/mysite/
##            python manage.py migrate
##            supervisorctl restart web

